version: '3'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: upskill
